# TCL File Generated by Component Editor 13.0sp1
# Sat Mar 07 11:20:08 CST 2020
# DO NOT MODIFY


# 
# mycpu "mycpu" v1.0
#  2020.03.07.11:20:08
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module mycpu
# 
set_module_property DESCRIPTION ""
set_module_property NAME mycpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mycpu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mycpu
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mycpu.v VERILOG PATH mycpu.v TOP_LEVEL_FILE
add_fileset_file uart_hs.v VERILOG PATH ../commoncode/uart_hs.v
add_fileset_file uart_recv_hs.v VERILOG PATH ../commoncode/uart_recv_hs.v
add_fileset_file uart_send_hs.v VERILOG PATH ../commoncode/uart_send_hs.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_readdata readdata Input 32
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_byteenable byteenable Output 4


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point irq0
# 
add_interface irq0 interrupt start
set_interface_property irq0 associatedAddressablePoint m0
set_interface_property irq0 associatedClock clock
set_interface_property irq0 associatedReset reset
set_interface_property irq0 irqScheme INDIVIDUAL_REQUESTS
set_interface_property irq0 ENABLED true
set_interface_property irq0 EXPORT_OF ""
set_interface_property irq0 PORT_NAME_MAP ""
set_interface_property irq0 SVD_ADDRESS_GROUP ""

add_interface_port irq0 inr_irq0_irq irq Input 32


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end uart_txd export Output 1
add_interface_port conduit_end debug export Output 8
add_interface_port conduit_end debug0 export Output 8
add_interface_port conduit_end debug1 export Output 8
add_interface_port conduit_end debug2 export Output 8
add_interface_port conduit_end debug3 export Output 8
add_interface_port conduit_end uart_rxd export Input 1

