#set_property PACKAGE_PIN N18 [get_ports {clk}]
set_property PACKAGE_PIN H20 [get_ports {led[0]}]
set_property PACKAGE_PIN K18 [get_ports {led[1]}]
set_property PACKAGE_PIN J20 [get_ports {led[2]}]
set_property PACKAGE_PIN L19 [get_ports {led[3]}]
set_property PACKAGE_PIN G19 [get_ports {keyin[0]}]
set_property PACKAGE_PIN J19 [get_ports {keyin[1]}]
set_property PACKAGE_PIN K19 [get_ports {keyin[2]}]
set_property PACKAGE_PIN L16 [get_ports {keyin[3]}]

set_property PACKAGE_PIN V13 [get_ports {uart0_rxd}]
set_property PACKAGE_PIN V15 [get_ports {uart0_txd}]
set_property PACKAGE_PIN V12 [get_ports {uart1_rxd}]
set_property PACKAGE_PIN U12 [get_ports {uart1_txd}]

set_property PACKAGE_PIN L17 [get_ports {debug[0]}]
set_property PACKAGE_PIN M19 [get_ports {debug[1]}]
set_property PACKAGE_PIN P18 [get_ports {debug[2]}]
set_property PACKAGE_PIN N17 [get_ports {debug[3]}]
set_property PACKAGE_PIN R18 [get_ports {debug[4]}]
set_property PACKAGE_PIN P19 [get_ports {debug[5]}]
set_property PACKAGE_PIN U20 [get_ports {debug[6]}]
set_property PACKAGE_PIN V20 [get_ports {debug[7]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyin[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {uart0_rxd}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart0_txd}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart1_rxd}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart1_txd}]

set_property IOSTANDARD LVCMOS33 [get_ports {debug[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug[7]}]
