import java.io.PrintStream;
import webServer.JspPage;
import webServer.Request;
import webServer.Session;
import webServer.Server;
public class config extends JspPage {
	public void doRequest() throws Exception{
out.println("<html>");
out.println("<head>");
out.println("<script>");
out.println("function on_load()");
out.println("{");
out.println(" setScroll(document.formMain.scroll.value);");
out.println("}");
out.println("function do_action(action,value,value1,value2,value3,value4,value5)");
out.println("{");
out.println("	document.formMain.scroll.value = getScroll();");
out.println("	document.formMain.action.value = action;");
out.println("	document.formMain.value.value = value;");
out.println("	document.formMain.value1.value = value1;");
out.println("	document.formMain.value2.value = value2;");
out.println("	document.formMain.value3.value = value3;");
out.println("	document.formMain.value4.value = value4;");
out.println("	document.formMain.value5.value = value5;");
out.println("	");
out.println("	document.formMain.submit();");
out.println("}");
out.println("function getScroll(){");
out.println(" var t;");
out.println(" if (document.documentElement && document.documentElement.scrollTop) {");
out.println("  t = document.documentElement.scrollTop;");
out.println(" } else if (document.body) {");
out.println("  t = document.body.scrollTop;");
out.println(" }");
out.println(" return t;");
out.println("}");
out.println("function setScroll(t){");
out.println(" if (document.documentElement && document.documentElement.scrollTop) {");
out.println("  document.documentElement.scrollTop = t;");
out.println(" } else if (document.body) {");
out.println("  document.body.scrollTop = t;");
out.println(" }");
out.println("}");
out.println("</script>");
out.println("</head>");
out.println("<body onload = \"on_load();\">");
out.print("<form name = 'formMain' action = '");
out.print(server.currentConfig.configPage);
out.println("' method = 'post'>");
out.println("<input type = hidden name = \"action\" id = \"action\">");
out.println("<input type = hidden name = \"value\" id = \"value\">");
out.println("<input type = hidden name = \"value1\" id = \"value1\">");
out.println("<input type = hidden name = \"value2\" id = \"value2\">");
out.println("<input type = hidden name = \"value3\" id = \"value3\">");
out.println("<input type = hidden name = \"value4\" id = \"value4\">");
out.println("<input type = hidden name = \"value5\" id = \"value5\">");

	Integer sc = (Integer)session.getPrivate("config_scroll_position");
	int scroll=0;
	if(sc!=null)
	{
		scroll=sc.intValue();
	}
out.print("<input type = hidden name = \"scroll\" id = \"scroll\" value = \"");
out.print(scroll);
out.println("\">");
out.println("</form>");
out.println("<table border=\"1\">");
out.println(" <tr>");
out.println("  <td><a href = \"javascript:do_action('reset');\">Apply config and reset server.</a></td>");
out.println("  <td><a href = \"javascript:do_action('shutdown');\">Shutdown server.</a></td>");
out.println("  <td><a href = \"javascript:do_action('makeXML');\">Write config to XML.</a></td>");
out.println("  <td><a href = \"javascript:do_action('exit');\">Exit.</a></td>");
out.println(" </tr>");
out.println("</table>");
out.println("<table border=\"1\">");
out.println(" <tr>");
out.println("  <td>port:</td>");
out.print("  <td><input type = text id = 'port' value = '");
out.print(server.currentConfig.port);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_port',port.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>SSLactive:</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("SSLactive",server.currentConfig.SSLactive));
out.println("</td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_SSLactive',SSLactive.value);\"></td>");
out.println(" </tr>");
if(server.currentConfig.SSLactive){out.println(" <tr>");
out.println("  <td>SSLport:</td>");
out.print("  <td><input type = text id = 'SSLport' value = '");
out.print(server.currentConfig.SSLport);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_SSLport',SSLport.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>clientKeysFile:</td>");
out.print("  <td><input type = text id = 'SSLclientKeysFile' value = '");
out.print(server.currentConfig.SSLclientKeysFile);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_SSLclientKeysFile',SSLclientKeysFile.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>SSLkeyStorePass:</td>");
out.print("  <td><input type = password id = 'SSLkeyStorePass' value = '");
out.print(server.currentConfig.SSLkeyStorePass);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_SSLkeyStorePass',SSLkeyStorePass.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>SSLkeyPassword:</td>");
out.print("  <td><input type = password id = 'SSLkeyPassword' value = '");
out.print(server.currentConfig.SSLkeyPassword);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_SSLkeyPassword',SSLkeyPassword.value);\"></td>");
out.println(" </tr>");
}out.println(" <tr>");
out.println("  <td>javaCompiler:</td>");
out.print("  <td><input type = text id = 'javaCompiler' value = '");
out.print(server.currentConfig.javaCompiler);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_javaCompiler',javaCompiler.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>defaultEncoding:</td>");
out.print("  <td><input type = text id = 'defaultEncoding' value = '");
out.print(server.currentConfig.defaultEncoding);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_defaultEncoding',defaultEncoding.value);\"></td>");
out.println(" </tr>");
out.println(" ");
out.println(" <tr>");
out.println("  <td>sessionExpires(in ms):</td>");
out.print("  <td><input type = text id = 'sessionExpires' value = '");
out.print(server.currentConfig.sessionExpires);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_sessionExpires',sessionExpires.value);\"></td>");
out.println(" </tr>");
out.println(" ");
out.println(" <tr>");
out.println("  <td>configPageEnabled:</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("configPageEnabled",server.currentConfig.configPageEnabled));
out.println("</td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_configPageEnabled',configPageEnabled.value);\"></td>");
out.println(" </tr>");
out.println(" ");
out.println(" <tr>");
out.println("  <td>configPageURL:</td>");
out.print("  <td><input type = text id = 'configPage' value = '");
out.print(server.currentConfig.configPage);
out.println("'></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_configPage',configPage.value);\"></td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td colspan = 3>");
out.println("  	config accessable IP.");
out.println("		<table border=\"1\" width = 100%>");
out.println("		 <tr>");
out.println("		  <td>IP/HOSTNAME</td>");
out.println("		  <td align=\"right\">operation</td>");
out.println("		 </tr>");
out.println("		");

		 for(int i=0;i<server.currentConfig.allowConfigIPs.size(); i++){
		  String s = (String)server.currentConfig.allowConfigIPs.get(i);
		out.println("		 <tr>");
out.print("		  <td>");
out.print(s);
out.println("</td>");
out.println("		  <td align=\"right\">");
out.print("		   <input type = button value = 'del' onclick = \"do_action('del_allowConfigIPs',");
out.print(i);
out.println(");\">");
out.println("		  </td>");
out.println("		 </tr>");
out.println("		");

		 }
		out.println("		 <tr>");
out.println("		  <td><input type = text id = 'allowConfigIPs' value = ''></td>");
out.println("		  <td align=\"right\"><input type = button value = 'add' onclick = \"do_action('add_allowConfigIPs',allowConfigIPs.value);\"></td>");
out.println("		 </tr>");
out.println("		</table>");
out.println("  </td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>config admin old password:</td>");
out.println("  <td><input type = password id = 'configPass1' value = ''></td>");
out.println("  <td>&nbsp;</td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>config admin new password:</td>");
out.println("  <td><input type = password id = 'configPass2' value = ''></td>");
out.println("  <td>&nbsp;</td>");
out.println(" </tr>");
out.println(" <tr>");
out.println("  <td>config admin new password confirm:</td>");
out.println("  <td><input type = password id = 'configPass3' value = ''></td>");
out.println("  <td><input type = button value = 'set' onclick = \"do_action('set_configPass',configPass1.value,configPass2.value,configPass3.value);\"></td>");
out.println(" </tr>");
out.println("</table>");
out.println("File System Setting:");
out.println("<table border=\"1\">");
out.println(" <tr>");
out.println("  <td>url</td>");
out.println("  <td>rootPath</td>");
out.println("  <td>allowList</td>");
out.println("  <td>allowUpLoad</td>");
out.println("  <td>allowDel</td>");
out.println("  <td>passWord</td>");
out.println("  <td>operation</td>");
out.println(" </tr>");

 for(int i=0;i<server.currentConfig.fileSystems.size(); i++){
  webServer.Config_FileSystem cfs = (webServer.Config_FileSystem) server.currentConfig.fileSystems.get(i);
out.println(" <tr>");
out.print("  <td>");
out.print(cfs.url);
out.println("</td>");
out.print("  <td>");
out.print(cfs.rootPath);
out.println("</td>");
out.print("  <td>");
out.print(cfs.allowList);
out.println("</td>");
out.print("  <td>");
out.print(cfs.allowUpLoad);
out.println("</td>");
out.print("  <td>");
out.print(cfs.allowDel);
out.println("</td>");
out.print("  <td>");
out.print(cfs.passWord==null?"&nbsp;":"******");
out.println("</td>");
out.println("  <td>");
out.print("   <input type = button value = 'edit' onclick = \"do_action('edit_fileSystem',");
out.print(i);
out.println(");\">");
out.print("   <input type = button value = 'del' onclick = \"do_action('del_fileSystem',");
out.print(i);
out.println(");\">");
out.println("  </td>");
out.println(" </tr>");

 }

Integer n = (Integer)session.getPrivate("edit_fileSystem");
if(n!=null){
int l = n.intValue();
  webServer.Config_FileSystem cfs = (webServer.Config_FileSystem) server.currentConfig.fileSystems.get(l);
out.println(" <tr>");
out.print("  <td><input type = text id = 'url' value = '");
out.print(cfs.url);
out.println("'></td>");
out.print("  <td><input type = text id = 'rootPath' value = '");
out.print(cfs.rootPath);
out.println("'></td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowList",cfs.allowList));
out.println("</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowUpLoad",cfs.allowUpLoad));
out.println("</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowDel",cfs.allowDel));
out.println("</td>");
out.print("  <td><input type = password id = 'passWord' value = '");
out.print(cfs.passWord==null?"":cfs.passWord);
out.println("'></td>");
out.println("  <td><input type = button value = 'update' onclick = \"do_action('upd_fileSystem',url.value,rootPath.value,allowList.value,allowUpLoad.value,allowDel.value,passWord.value);\"></td>");
out.println(" </tr>");
}else{out.println(" <tr>");
out.println("  <td><input type = text id = 'url' value = ''></td>");
out.println("  <td><input type = text id = 'rootPath' value = ''></td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowList",false));
out.println("</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowUpLoad",false));
out.println("</td>");
out.print("  <td>");
out.print(webServer.ConfigServlet.getPullDown("allowDel",false));
out.println("</td>");
out.println("  <td><input type = password id = 'passWord' value = ''></td>");
out.println("  <td><input type = button value = 'add' onclick = \"do_action('add_fileSystem',url.value,rootPath.value,allowList.value,allowUpLoad.value,allowDel.value,passWord.value);\"></td>");
out.println(" </tr>");
}out.println("</table>");
out.println("</table>");
out.println("JSP Setting:");
out.println("<table border=\"1\">");
out.println(" <tr>");
out.println("  <td>url</td>");
out.println("  <td>rootPath</td>");
out.println("  <td>operation</td>");
out.println(" </tr>");

 for(int i=0;i<server.currentConfig.jspProcessors.size(); i++){
  webServer.Config_JspProcessor cjp = (webServer.Config_JspProcessor) server.currentConfig.jspProcessors.get(i);
out.println(" <tr>");
out.print("  <td>");
out.print(cjp.url);
out.println("</td>");
out.print("  <td>");
out.print(cjp.rootPath);
out.println("</td>");
out.println("  <td>");
out.print("   <input type = button value = 'edit' onclick = \"do_action('edit_jspProcessors',");
out.print(i);
out.println(");\">");
out.print("   <input type = button value = 'del' onclick = \"do_action('del_jspProcessors',");
out.print(i);
out.println(");\">");
out.println("  </td>");
out.println(" </tr>");

 }

n = (Integer)session.getPrivate("edit_jspProcessors");
if(n!=null){
int l = n.intValue();
  webServer.Config_JspProcessor cjp = (webServer.Config_JspProcessor) server.currentConfig.jspProcessors.get(l);
out.println(" <tr>");
out.print("  <td><input type = text id = 'JSPurl' value = '");
out.print(cjp.url);
out.println("'></td>");
out.print("  <td><input type = text id = 'JSProotPath' value = '");
out.print(cjp.rootPath);
out.println("'></td>");
out.println("  <td><input type = button value = 'update' onclick = \"do_action('upd_jspProcessors',JSPurl.value,JSProotPath.value);\"></td>");
out.println(" </tr>");
}else{out.println(" <tr>");
out.println("  <td><input type = text id = 'JSPurl' value = ''></td>");
out.println("  <td><input type = text id = 'JSProotPath' value = ''></td>");
out.println("  <td><input type = button value = 'add' onclick = \"do_action('add_jspProcessors',JSPurl.value,JSProotPath.value);\"></td>");
out.println(" </tr>");
}out.println("</table>");
out.println("</table>");
out.println("servlet Setting:");
out.println("<table border=\"1\">");
out.println(" <tr>");
out.println("  <td>url</td>");
out.println("  <td>class</td>");
out.println("  <td>operation</td>");
out.println(" </tr>");

 for(int i=0;i<server.currentConfig.servlets.size(); i++){
  webServer.Config_Servlet cs = (webServer.Config_Servlet) server.currentConfig.servlets.get(i);
out.println(" <tr>");
out.print("  <td>");
out.print(cs.url);
out.println("</td>");
out.print("  <td>");
out.print(cs.classFileName);
out.println("</td>");
out.println("  <td>");
out.print("   <input type = button value = 'edit' onclick = \"do_action('edit_servlets',");
out.print(i);
out.println(");\">");
out.print("   <input type = button value = 'del' onclick = \"do_action('del_servlets',");
out.print(i);
out.println(");\">");
out.println("  </td>");
out.println(" </tr>");

 }

n = (Integer)session.getPrivate("edit_servlets");
if(n!=null){
int l = n.intValue();
  webServer.Config_Servlet cs = (webServer.Config_Servlet) server.currentConfig.servlets.get(l);
out.println(" <tr>");
out.print("  <td><input type = text id = 'ServletUrl' value = '");
out.print(cs.url);
out.println("'></td>");
out.print("  <td><input type = text id = 'class' value = '");
out.print(cs.classFileName);
out.println("'></td>");
out.println("  <td><input type = button value = 'update' onclick = \"do_action('upd_servlets',ServletUrl.value,class.value);\"></td>");
out.println(" </tr>");
}else{out.println(" <tr>");
out.println("  <td><input type = text id = 'ServletUrl' value = ''></td>");
out.println("  <td><input type = text id = 'class' value = ''></td>");
out.println("  <td><input type = button value = 'add' onclick = \"do_action('add_servlets',ServletUrl.value,class.value);\"></td>");
out.println(" </tr>");
}out.println("</table>");
out.println("</body>");
out.println("</html>");
	}
}
